// Firebase configuration - auto-generated by AppGen
// Do not edit this file directly - use the Authentication settings in AppGen

import { initializeApp, getApps, getApp, FirebaseApp } from 'firebase/app';
import { getAuth, initializeAuth, getReactNativePersistence, Auth } from 'firebase/auth';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';

export const firebaseConfig = {
  "apiKey": "AIzaSyAZ1ZuebrW1OC6jSaPEaZXzBogH0KQ_rJU",
  "authDomain": "ezypzy-61a1f.firebaseapp.com",
  "projectId": "ezypzy-61a1f",
  "storageBucket": "ezypzy-61a1f.firebasestorage.app",
  "messagingSenderId": "124297885826",
  "appId": "1:124297885826:web:7ab82f30a442707c771c9b",
  "measurementId": "G-LTWXBMT2MC"
};

// Only email authentication is enabled
export const enabledAuthMethods: string[] = ["email"];

let app: FirebaseApp | null = null;
let auth: Auth | null = null;
let initError: Error | null = null;

// Initialize Firebase lazily
export const getFirebaseAuth = (): Auth | null => {
  if (auth) return auth;
  if (initError) return null;
  
  try {
    // Initialize app
    if (getApps().length === 0) {
      app = initializeApp(firebaseConfig);
    } else {
      app = getApp();
    }
    
    // Initialize Auth with AsyncStorage persistence for React Native
    if (Platform.OS === 'web') {
      auth = getAuth(app);
    } else {
      auth = initializeAuth(app, {
        persistence: getReactNativePersistence(AsyncStorage)
      });
    }
    
    return auth;
  } catch (error) {
    console.log('Firebase auth initialization error:', error);
    initError = error as Error;
    return null;
  }
};

export { auth };
